name: Exports AWS Secrets Manager's secrets as environment variables
description: Exports AWS Secrets Manager's secrets as environment variables
runs:
  using: composite
  steps:
    - run: |
        echo '::warning::This action was deprecated. Please use suzuki-shunsuke/tfaction/js action.'
      shell: bash
    - uses: Taiki130/tfaction/js@feature/detect-local-module-changed-for-terragrunt
      id: main
      with:
        action: export-aws-secrets-manager
